# Generated by Django 2.2.7 on 2019-11-09 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0002_auto_20191106_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone_book.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone_book.Person'),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
